server:
  port: 8770
 
spring:
  profiles: peer3
   
eureka:
  instance:
    hostname: peer3
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8769/eureka/
    register-with-eureka: true
    fetch-registry: true